version: '3'

services:
  api:
    image: mlichtblau/wirvvsvirus/api:latest
    build:
      context: src
      dockerfile: api.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .api.env

  postgres:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .postgres.env

  adminer:
    image: adminer:4.7

volumes:
  postgresdata:

