runtime: python27
api_version: 1
threadsafe: true

skip_files:
- (?!^www)

handlers:
- url: /(.*\.(js|css|svg|png)(|\.map))$
  static_files: www/\1
  upload: www/(.*)(|\.map)
- url: /.*
  static_files: www/index.html
  upload: www/.*
