runtime: python27
threadsafe: true
service: app

skip_files:
- (?!^www)

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
